[project]
name = "cwc-mo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.11.26",
    "pandas>=2.2.3",
    "polars>=1.26.0",
    "scipy>=1.15.2",
]
